name : Docs Deploy

on: 
  ## TODO: support docs versioning
  push:
    branches: [master, "release/v*"]
  pull_request:
    branches: [master]
  release:
    types: [published, edited]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6
      - name: Setup Environment
        run: |
          sudo apt-get update && sudo apt-get install -y git
          python -m pip install --upgrade pip
          pip install "./src/development[test]" "./src/runtime[all]"
          python -m pip install -r docs/requirements.txt
      - name: Build Docs
        run: |
          make -C docs clean
          sphinx-multiversion docs docs/_build/html
          cp docs/gh-pages-index.html docs/_build/html/index.html
      - name: Deploy Docs
        # if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@users.noreply.github.com"
          git fetch --all && git checkout gh-pages
          for dirname in docs/_build/html/*; do mv "$dirname" $(basename "$dirname") && git add $(basename "$dirname"); done
          git commit -m "Added HTML docs"
          git push origin gh-pages
